### ISSUE TITLE
Update icons for obscure options

### ISSUE THREAD

**Issue by cstiens** [guardianproject/ObscuraCam#107]

**Comment by cstiens** [comment]
@N-Pex I've attached update icons for the obscure options. I'm going to try to find some more mask options. The one we have looks low-res.

![ic_crowd-pixel](https://user-images.githubusercontent.com/1434597/28941894-11873148-785f-11e7-9a9c-ab4a1283f1fd.png)
![ic_pixelate](https://user-images.githubusercontent.com/1434597/28941893-1185cac4-785f-11e7-8a2c-3dfe4e51065f.png)
![ic_redact](https://user-images.githubusercontent.com/1434597/28941896-118cfcea-785f-11e7-9411-56cc6d06fb82.png)
![ic_remove](https://user-images.githubusercontent.com/1434597/28941895-118b4f30-785f-11e7-9bb6-9e03d1b31929.png)

**Comment by n8fr8** [comment]
Nice!

**Comment by tiffrobo** [comment]
> Thanks, they look great! What about the names, I notice that in your mockup they are somewhat different (e.g. "Clear Tag" is called "Remove")?

Yes, please change 'clear tag' to 'Remove'. Pixelate, Mask and Redact are the same. @DavidMOliver and I talked about changing from Crowd Pixel to Inverse. Though, I don't have a good sense of how well people understand Crowd Pixel. @n8fr8 any insight here? 

At the very least, regardless of the name, once they tap it, it's clear what it does.

**Comment by cstiens** [comment]
Hey! Oops. The last comment was from me. I was just using Tiffany's computer and didn't realize she was logged in instead of me. :)

**Comment by n8fr8** [comment]
Inverse is fine!

**Comment by cstiens** [comment]
I found these great masks on Creative Market. I've attached .pngs

<img width="896" alt="screenshot 2017-08-07 15 24 45" src="https://user-images.githubusercontent.com/1434597/29044328-925f6cb8-7b84-11e7-8384-9025862f81ae.png">

[ic_maskv1.zip](https://github.com/guardianproject/ObscuraCam/files/1206059/ic_maskv1.zip)

**Comment by n8fr8** [comment]
Hmm... might be too much, though I did include the luchodar wrestling masks.
