### ISSUE TITLE
Google Console Request

### ISSUE THREAD

**Issue by ingfabby** [guardianproject/ObscuraCam#141]
Let us know whether your app requires login credentials
ObscuraCam
ObscuraCam
Dec 15, 2021 13:46
If parts of your app are restricted based on login credentials, sign in details, memberships, location, or other forms of authentication, you must provide instructions on how to access them. This helps us review your app for compliance with Google Play policies.

If your app does not have any access restrictions, no further action is required from you.

If we're unable to review your app (for example, because part of your app requires login credentials), your app may be blocked from releasing new updates, or removed from Google Play.

If your update is rejected or your app is removed, visit the Help Center to learn how to resubmit your app for review. You can complete these steps without contacting or waiting for a reply from the policy support team.

**Comment by n8fr8** [comment]
obscuracam has no access restrictions, so we are all good!
