### ISSUE TITLE
App is not recognized as Camera app and cannot be used/set as default since Android 11

### ISSUE THREAD

**Issue by rugk** [guardianproject/ObscuraCam#142]
## STR

1. Install the app.
2. You cannot actually set the app as the default app for the camera or even choose it when such an intend is sent/other app requests pictures.
3. It e.g. looks like this (you can use "Camera Folder" linked below to reproduce this):
  ![camer-app-selection](https://user-images.githubusercontent.com/11966684/156040484-caf78f62-73be-46d1-ad0e-d2d79cc0e62f.png)

Also apps [like Camera Folder](https://f-droid.org/de/packages/de.k3b.android.camerafolder/) won't work like this, because they don't recognize this app as a camera app.

# System

Device: Pixel 4
OS: Android 12, CalyxOS 3.2.0
source: F-Droid
version: v5.3.1

## Possibly solution

It also apparently affects other camera apps, see https://github.com/SimpleMobileTools/Simple-Camera-Abandoned/issues/310 or [OpenCamera](https://sourceforge.net/p/opencamera/discussion/qa/thread/9b0292b70d/).
Apparently, the issue is related to how [camera apps are handled since Android 11](https://www.theverge.com/2020/8/20/21376391/google-android-11-third-party-camera-picker-intents).

**Comment by n8fr8** [comment]
ObscuraCam isn't intended to be a primary camera app. It is meant to share existing photos and videos too.

**Comment by rugk** [comment]
Hmm okay, but I thought it was selectable in the past. Nevermind then…
